---
apiVersion: "proxy.otoroshi.io/v1"
kind: "AuthModule"
spec:
  _loc:
    tenant: "default"
    teams:
    - "default"
  type: "basic"
  id: "auth_mod_dev_f7b3446f-dee2-424f-849f-e6c1e372ae38"
  name: "In memory authentication provider"
  desc: "In memory authentication provider description"
  basicAuth: false
  webauthn: false
  clientSideSessionEnabled: true
  sessionMaxAge: 86400
  metadata: {}
  tags: []
  users:
  - name: "Bob"
    password: "$2a$10$kAIZJJg9PTTTFignXEwKCepIDg851O9kK1Eh46QgeNTUAe.B6PvYC"
    email: "wasm@oto.tools"
    metadata: {}
    tags: []
    webauthn: null
    rights:
    - tenant: "*:rw"
      teams:
      - "*:rw"
    adminEntityValidators: {}
  sessionCookieValues:
    httpOnly: true
    secure: false
  userValidators: []
