---
apiVersion: "proxy.otoroshi.io/v1"
kind: "Route"
metadata:
  name: "route_d07e66aa7-62b0-41c8-b804-325198c59692"
spec:
  _loc:
    tenant: "default"
    teams:
    - "default"
  id: "route_d07e66aa7-62b0-41c8-b804-325198c59692"
  name: "websocket"
  description: "A new route"
  tags: []
  metadata:
    otoroshi-core-use-akka-http-ws-client: "true"
  enabled: true
  debug_flow: false
  export_reporting: false
  capture: false
  groups:
  - "default"
  frontend:
    domains:
    - "websocket.oto.tools"
    strip_path: true
    exact: false
    headers: {}
    query: {}
    methods: []
  backend:
    targets:
    - id: "target_1"
      hostname: "localhost"
      port: 4444
      tls: false
      weight: 1
      predicate:
        type: "AlwaysMatch"
      protocol: "HTTP/1.1"
      ip_address: null
      tls_config:
        certs: []
        trusted_certs: []
        enabled: false
        loose: false
        trust_all: false
    root: "/"
    rewrite: false
    load_balancing:
      type: "RoundRobin"
    client:
      retries: 1
      max_errors: 20
      retry_initial_delay: 50
      backoff_factor: 2
      call_timeout: 30000
      call_and_stream_timeout: 120000
      connection_timeout: 10000
      idle_timeout: 60000
      global_timeout: 30000
      sample_interval: 2000
      proxy: {}
      custom_timeouts: []
      cache_connection_settings:
        enabled: false
        queue_size: 2048
    health_check:
      enabled: false
      url: ""
      timeout: 5000
      healthyStatuses: []
      unhealthyStatuses: []
  backend_ref: null
  plugins:
  - enabled: true
    debug: false
    plugin: "cp:otoroshi.next.plugins.WebsocketTypeValidator"
    include: []
    exclude: []
    config:
      allowed_format: "text"
      reject_strategy: "drop"
    plugin_index:
      validate_access: 5
    nodeId: "cp:otoroshi.next.plugins.WebsocketTypeValidator"
  - enabled: true
    debug: false
    plugin: "cp:otoroshi.next.plugins.WebsocketSizeValidator"
    include: []
    exclude: []
    config:
      client_max_payload: 140
      upstream_max_payload: 10000
      reject_strategy: "drop"
    plugin_index:
      validate_access: 7
      transform_response: 0
    nodeId: "cp:otoroshi.next.plugins.WebsocketSizeValidator"
  - enabled: true
    debug: false
    plugin: "cp:otoroshi.next.plugins.WasmWebsocketTransformer"
    include: []
    exclude: []
    config:
      source:
        kind: "wasmo"
        path: "test-1.0.2-dev.wasm"
        opts: {}
      memoryPages: 2000
      functionName: ""
      config: {}
      allowedHosts: []
      allowedPaths: {}
      wasi: true
      opa: false
      authorizations:
        httpAccess: false
        proxyHttpCallTimeout: 5000
        globalDataStoreAccess:
          read: false
          write: false
        pluginDataStoreAccess:
          read: false
          write: false
        globalMapAccess:
          read: false
          write: false
        pluginMapAccess:
          read: false
          write: false
        proxyStateAccess: false
        configurationAccess: false
      instances: 1
      killOptions:
        immortal: false
        max_calls: 2147483647
        max_memory_usage: 0
        max_avg_call_duration: 0
        max_unused_duration: 300000
    plugin_index:
      transform_response: 1
    nodeId: "cp:otoroshi.next.plugins.WasmWebsocketTransformer"
  - enabled: true
    debug: false
    plugin: "cp:otoroshi.next.plugins.NgAuthModuleUserExtractor"
    include: []
    exclude: []
    config:
      auth_module: null
      module: "auth_mod_dev_f7b3446f-dee2-424f-849f-e6c1e372ae38"
    plugin_index:
      validate_access: 3
    nodeId: "cp:otoroshi.next.plugins.NgAuthModuleUserExtractor"
  - enabled: true
    debug: false
    plugin: "cp:otoroshi.next.plugins.ApikeyCalls"
    include: []
    exclude: []
    config:
      extractors:
        basic:
          enabled: true
          header_name: null
          query_name: null
        custom_headers:
          enabled: true
          client_id_header_name: null
          client_secret_header_name: null
        client_id:
          enabled: true
          header_name: null
          query_name: null
        jwt:
          enabled: true
          secret_signed: true
          keypair_signed: true
          include_request_attrs: false
          max_jwt_lifespan_sec: null
          header_name: null
          query_name: null
          cookie_name: null
      routing:
        enabled: false
      validate: true
      mandatory: true
      pass_with_user: true
      wipe_backend_request: true
      update_quotas: true
    plugin_index:
      validate_access: 8
      transform_request: 0
      match_route: 0
    nodeId: "cp:otoroshi.next.plugins.ApikeyCalls"
